dist: trusty
language: python
env:
  - ONNX_VERSION="1.1.2" ONNX_ML=1
  - ONNX_VERSION="1.2.1" ONNX_ML=1

addons:
  apt:
    packages:
      - build-essential
      - curl
      - git

python:
    - "2.7"
    - "3.5"
    - "3.6"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      curl -L https://repo.continuum.io/miniconda/Miniconda2-4.3.21-Linux-x86_64.sh -o $HOME/miniconda.sh;
      PYTHON_VER="2.7";
    else
      curl -L https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -o $HOME/miniconda.sh;
      PYTHON_VER="3.6m";
    fi
  - cd $HOME && bash miniconda.sh -b -p $HOME/miniconda
  - printenv
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build
  - conda install -c conda-forge cmake
  - git clone --recursive https://github.com/pytorch/pytorch.git
  - cd pytorch && ./scripts/build_anaconda.sh --install-locally -DUSE_MPI=OFF
  - cd $TRAVIS_BUILD_DIR && pip install -r requirements-dev.txt
  - conda install -c conda-forge protobuf numpy cmake
  - cd $TRAVIS_BUILD_DIR && pip install -I git+https://github.com/onnx/onnx@rel-$ONNX_VERSION
  - cd $TRAVIS_BUILD_DIR && export PYTHONPATH=pwd

script:
    - python -m pytest --cov=onnxmltools --cov-report=term --cov-report=html --cov-report=xml tests

